In [1]:
import pandas as pd
import numpy as np

In [2]:
ola=pd.read_excel("Bengaluru Ola.xlsx")
ola.head(10)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for Cancelling by Customer,Cancelled Rides by Driver,Reason for Cancelling by Driver,Incomplete Rides,Incomplete Rides Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating
0,2024-01-28,06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,NaN,0,NaN,0,NaN,868.06,Wallet,28.50,4.4,4.4
1,2024-01-26,03:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-15,16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-02,22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-30,22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,0,NaN,1,Other Issue,NaN,NaN,NaN,NaN,NaN
5,2024-01-14,20:00:00,CNR8720322,Incomplete,787277,Prime Plus,Area-46,Area-21,NaN,NaN,...,NaN,0,NaN,1,Vehicle Breakdown,NaN,NaN,NaN,NaN,NaN
6,2024-01-17,21:00:00,CNR8611757,Success,329974,Prime Sedan,Area-38,Area-26,19.95,5.01,...,NaN,0,NaN,0,NaN,348.04,Card,25.18,4.5,4.7
7,2024-01-30,00:00:00,CNR4039598,Success,663054,eBike,Area-47,Area-8,15.27,23.29,...,NaN,0,NaN,0,NaN,56.33,UPI,17.67,3.6,3.3
8,2024-01-22,08:00:00,CNR7516851,Success,656116,Prime SUV,Area-11,Area-35,18.45,18.37,...,NaN,0,NaN,0,NaN,1971.38,UPI,24.94,3.2,3.7
9,2024-01-11,05:00:00,CNR0890407,Cancelled by Driver,676510,Mini,Area-9,Area-43,NaN,NaN,...,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
ola.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled  by Customer',
       'Reason for Cancelling by Customer', 'Cancelled Rides by Driver',
       'Reason for Cancelling by Driver', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Payment Method',
       'Ride Distance', 'Driver Ratings', 'Customer Rating'],
      dtype='object')

In [4]:
uber=pd.read_excel("Bengaluru Uber.xlsx")
uber.head(10)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer Reason,Cancelled Rides by Driver Reason,Incomplete Ride Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Ratings
0,2024-01-15,14:15:00,BKG000001,Success,CUST40172,eBike,Benson Town,Magadi Road,6.83,7.45,NaN,NaN,NaN,881.71,UPI,2.52,1.7,3.2
1,2024-01-28,09:50:00,BKG000002,Incomplete,CUST43954,Moto,Cox Town,Indiranagar,5.11,5.31,NaN,NaN,Vehicle Breakdown,0.00,NaN,0.00,NaN,NaN
2,2024-01-06,03:33:00,BKG000003,Success,CUST95942,Go Sedan,Mahadevapura,Whitefield,14.90,9.64,NaN,NaN,NaN,1458.30,Wallet,26.20,1.1,2.4
3,2024-01-07,01:28:00,BKG000004,Success,CUST15911,Go Sedan,RT Nagar,Nagarbhavi,10.53,9.50,NaN,NaN,NaN,1323.55,Wallet,26.20,3.1,3.7
4,2024-01-07,07:32:00,BKG000005,Success,CUST94242,Uber Go,Basavanagudi,Vijayanagar,8.83,5.75,NaN,NaN,NaN,1999.27,Cash,27.58,2.1,2.8
5,2024-01-28,11:31:00,BKG000006,Success,CUST18676,Moto,Bannerghatta Road,Devanahalli,12.90,6.33,NaN,NaN,NaN,1910.96,Cash,10.96,1.7,2.7
6,2024-01-20,04:00:00,BKG000007,Success,CUST90215,Premier,Electronic City,Mahadevapura,12.18,8.27,NaN,NaN,NaN,398.67,Card,26.12,2.1,3.9
7,2024-01-27,21:17:00,BKG000008,Success,CUST66438,Moto,Banashankari,Anekal,9.38,8.57,NaN,NaN,NaN,1202.21,Card,12.62,3.1,4.5
8,2024-01-18,20:49:00,BKG000009,Success,CUST40366,Go Sedan,Kadugodi,Hosur Road,3.14,4.22,NaN,NaN,NaN,1723.07,UPI,9.33,2.4,3.7
9,2024-01-24,22:19:00,BKG000010,Cancelled by Customer,CUST87199,eBike,Vijayanagar,RT Nagar,10.62,8.95,Change of plans,NaN,NaN,0.00,NaN,0.00,NaN,NaN

In [5]:
uber.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer Reason',
       'Cancelled Rides by Driver Reason', 'Incomplete Ride Reason',
       'Booking Value', 'Payment Method', 'Ride Distance', 'Driver Ratings',
       'Customer Ratings'],
      dtype='object')

In [6]:
uber.rename(columns={"Customer Ratings":"Customer Rating"},inplace=True)

In [7]:
ola["Company"]="Ola"
uber["Company"]="Uber"

In [8]:
common_cols=['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT','Booking Value', 'Payment Method',
       'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Company']

In [9]:
ola=ola[common_cols]
uber=uber[common_cols]

In [10]:
rides=pd.concat([ola,uber],ignore_index=True)

In [11]:
rides.shape

(249999, 16)

In [12]:
rides["Company"].value_counts()

Company
Uber    200000
Ola      49999
Name: count, dtype: int64

In [13]:
rides.isnull().sum()

Date                   0
Time                   0
Booking ID             0
Booking Status         0
Customer ID            0
Vehicle Type           0
Pickup Location        0
Drop Location          0
Avg VTAT           16515
Avg CTAT           16515
Booking Value      16515
Payment Method     92351
Ride Distance      16515
Driver Ratings     92351
Customer Rating    92351
Company                0
dtype: int64

In [14]:
missing=rides.isnull().sum()
missing_percent=(missing/len(rides))*100
print(missing_percent.sort_values(ascending=False))

Payment Method     36.940548
Driver Ratings     36.940548
Customer Rating    36.940548
Avg VTAT            6.606026
Avg CTAT            6.606026
Booking Value       6.606026
Ride Distance       6.606026
Date                0.000000
Time                0.000000
Booking ID          0.000000
Booking Status      0.000000
Customer ID         0.000000
Vehicle Type        0.000000
Pickup Location     0.000000
Drop Location       0.000000
Company             0.000000
dtype: float64

In [15]:
rides["Booking Status"].value_counts(dropna=False)

Booking Status
Success                  157648
Cancelled by Driver       45483
Incomplete                28878
Cancelled by Customer     17990
Name: count, dtype: int64

In [16]:
rides.groupby("Booking Status").agg({
    "Booking Value":"count",
    "Ride Distance":"count",
    "Customer Rating":"count"
})

                       Booking Value  Ride Distance  Customer Rating
Booking Status
Cancelled by Customer          14191          14191                0
Cancelled by Driver            35873          35873                0
Incomplete                     25772          25772                0
Success                       157648         157648           157648

In [17]:
rides["Booking Status"].value_counts()

Booking Status
Success                  157648
Cancelled by Driver       45483
Incomplete                28878
Cancelled by Customer     17990
Name: count, dtype: int64

In [18]:
def ride_outcome(status):
    if status=="Success":
        return "Success"
    elif "Cancelled" in status:
        return "Cancelled"
    else :
        return "Incomplete"

rides["Ride_outcome"]=(rides["Booking Status"].apply(ride_outcome))

In [19]:
rides["Ride_outcome"].value_counts()

Ride_outcome
Success       157648
Cancelled      63473
Incomplete     28878
Name: count, dtype: int64

In [20]:
pd.crosstab(rides["Company"],rides["Ride_outcome"],normalize="index")*100

Ride_outcome  Cancelled  Incomplete    Success
Company
Ola           26.818536    6.212124  66.969339
Uber          25.032000   12.886000  62.082000

In [21]:
pricing_df=rides.dropna(
    subset=["Booking Value","Ride Distance"]
).copy()
pricing_df["Fare_per_KM"]=(pricing_df["Booking Value"]/pricing_df["Ride Distance"])

In [22]:
pricing_df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Rating,Company,Ride_outcome,Fare_per_KM
0,2024-01-28,06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,868.06,Wallet,28.50,4.4,4.4,Ola,Success,30.458246
6,2024-01-17,21:00:00,CNR8611757,Success,329974,Prime Sedan,Area-38,Area-26,19.95,5.01,348.04,Card,25.18,4.5,4.7,Ola,Success,13.822081
7,2024-01-30,00:00:00,CNR4039598,Success,663054,eBike,Area-47,Area-8,15.27,23.29,56.33,UPI,17.67,3.6,3.3,Ola,Success,3.187889
8,2024-01-22,08:00:00,CNR7516851,Success,656116,Prime SUV,Area-11,Area-35,18.45,18.37,1971.38,UPI,24.94,3.2,3.7,Ola,Success,79.044908
10,2024-01-12,07:00:00,CNR5699767,Success,559381,Prime Sedan,Area-43,Area-42,18.09,14.09,1130.15,Card,13.15,3.1,3.0,Ola,Success,85.942966

In [23]:
print(type(rides["Time"].iloc[0]))

<class 'datetime.time'>

In [24]:
rides["Hour"]=rides["Time"].apply(lambda x:x.hour)

In [25]:
rides[["Time","Hour"]].head()

       Time  Hour
0  06:00:00     6
1  03:00:00     3
2  16:00:00    16
3  22:00:00    22
4  22:00:00    22

In [26]:
def bucket(hour):
    if 5<=hour<12:
        return "Morning"
    elif 12<=hour<17:
        return "Afternoon"
    elif 17<=hour<22:
        return "Evening"
    else:
        return"Night"

rides["Time_bucket"]=rides["Hour"].apply(bucket)

In [27]:
rides["Time_bucket"].value_counts()

Time_bucket
Morning      72895
Night        72608
Evening      52259
Afternoon    52237
Name: count, dtype: int64

In [28]:
rides["Date"]=pd.to_datetime(rides["Date"])
rides["Day_of_Week"]=(rides["Date"].dt.day_name())

In [29]:
rides["Day_of_Week"].value_counts()

Day_of_Week
Monday       40586
Tuesday      40506
Wednesday    38973
Thursday     32629
Friday       32614
Sunday       32417
Saturday     32274
Name: count, dtype: int64

In [30]:
rides["Day_Type"]=np.where(rides["Day_of_Week"].isin(["Saturday","Sunday"]),"Weekend","Weekday")

In [31]:
pricing_df["Distance_Category"]=pd.cut(pricing_df["Ride Distance"],bins=[0,5,10,20,1000],labels=["Short","Medium","Long","Very Long"])

In [32]:
pricing_df["Revenue_Category"]=pd.cut(pricing_df["Booking Value"],bins=[0,200,500,1000,10000],labels=["Low","Medium","High","Premium"])

In [33]:
rating_df=rides.dropna(subset=["Customer Rating","Driver Ratings"]).copy()
rating_df["Rating_Difference"]=(rating_df["Customer Rating"]-rating_df["Driver Ratings"])

In [34]:
pricing_df.groupby("Company")["Fare_per_KM"].describe()

,count,mean,std,min,25%,50%,75%,max
Company,,,,,,,,
Ola,33484.0,82.363945,145.347591,1.015212,21.032266,40.145266,77.334808,1959.000000
Uber,124164.0,119.851919,176.039285,1.690587,34.540755,65.826854,123.853412,1954.068627

In [35]:
pd.crosstab(rides["Company"],rides["Ride_outcome"],normalize="index")*100

Ride_outcome  Cancelled  Incomplete    Success
Company
Ola           26.818536    6.212124  66.969339
Uber          25.032000   12.886000  62.082000

In [36]:
vehicle_map = {
    "Bike":"Bike",
    "eBike":"Bike",
    "Auto":"Auto",
    "Mini":"Economy",
    "Prime Sedan":"Sedan",
    "Prime SUV":"SUV",
    "Prime Plus":"Premium",
    "Moto":"Bike",
    "Uber Go":"Economy",
    "Go Sedan":"Sedan",
    "UberXL":"SUV",
    "Premier":"Premium",
    "Non-AC Taxi":"Economy",
    "eBike":"Bike"
}

In [37]:
rides["Vehicle_Category"] = (rides["Vehicle Type"].map(vehicle_map))

In [38]:
rides.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Ride Distance,Driver Ratings,Customer Rating,Company,Ride_outcome,Hour,Time_bucket,Day_of_Week,Day_Type,Vehicle_Category
0,2024-01-28,06:00:00,CNR1721175,Success,329258,Auto,Area-3,Area-2,5.42,18.46,...,28.5,4.4,4.4,Ola,Success,6,Morning,Sunday,Weekend,Auto
1,2024-01-26,03:00:00,CNR2871422,Cancelled by Driver,201414,Mini,Area-7,Area-6,NaN,NaN,...,NaN,NaN,NaN,Ola,Cancelled,3,Night,Friday,Weekday,Economy
2,2024-01-15,16:00:00,CNR6875935,Cancelled by Driver,301629,Bike,Area-40,Area-24,NaN,NaN,...,NaN,NaN,NaN,Ola,Cancelled,16,Afternoon,Monday,Weekday,Bike
3,2024-01-02,22:00:00,CNR6798834,Cancelled by Driver,319684,Prime Sedan,Area-11,Area-24,NaN,NaN,...,NaN,NaN,NaN,Ola,Cancelled,22,Night,Tuesday,Weekday,Sedan
4,2024-01-30,22:00:00,CNR9661713,Incomplete,330283,Bike,Area-41,Area-45,NaN,NaN,...,NaN,NaN,NaN,Ola,Incomplete,22,Night,Tuesday,Weekday,Bike

In [39]:
pd.crosstab(pricing_df["Company"],pricing_df["Revenue_Category"],normalize="index")*100

Revenue_Category       Low     Medium       High    Premium
Company
Ola               7.648429  15.711982  25.394218  51.245371
Uber              7.801778  15.383686  25.766728  51.047808

In [56]:
rides.to_csv("Total_Data_Ola&Uber.csv",index=False)

In [42]:
rating_df.groupby("Company")["Customer Rating"].mean()

Company
Ola     4.001726
Uber    3.002977
Name: Customer Rating, dtype: float64

In [43]:
rating_df.groupby("Company")["Driver Ratings"].mean()

Company
Ola     4.003040
Uber    2.997194
Name: Driver Ratings, dtype: float64

In [44]:
pricing_df.groupby("Company")["Booking Value"].mean()

Company
Ola     1023.374286
Uber     634.848029
Name: Booking Value, dtype: float64

In [51]:
pricing_df.groupby(["Company","Vehicle_Category"])["Fare_per_KM"].mean().sort_values(ascending=False)

Company  Vehicle_Category
Uber     Economy             121.441198
         SUV                 120.827111
         Sedan               119.796497
         Premium             118.654622
         Bike                118.419525
Ola      SUV                  85.569232
         Economy              83.058661
         Sedan                82.212887
         Bike                 81.845565
         Premium              81.817240
         Auto                 80.226981
Name: Fare_per_KM, dtype: float64

In [52]:
pricing_df = rides.dropna(
    subset=["Booking Value","Ride Distance"]
).copy()

In [53]:
pricing_df.to_csv("Final_Rides_Pricing.csv", index=False)

In [50]:
pricing_df["Fare_per_KM"] = (pricing_df["Booking Value"]/pricing_df["Ride Distance"])

In [54]:
rides["Fare_per_KM"] = (
    rides["Booking Value"]
    /
    rides["Ride Distance"]
)